global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'laravel-app'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['app:8000']

rule_files:
  - "/etc/prometheus/alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']