version: '3.8'

services:
  app:
    build: .
    container_name: wmo-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - wmo-network
    depends_on:
      - db
      - nginx

  db:
    image: mysql:8.0
    container_name: wmo-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wmo_db
      MYSQL_USER: wmo_user
      MYSQL_PASSWORD: wmo_pass
      MYSQL_ROOT_PASSWORD: root_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wmo-network

  nginx:
    image: nginx:latest
    container_name: wmo-api-nginx
    restart: unless-stopped
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - wmo-network
    ports:
      - "80:80"

networks:
  wmo-network:

volumes:
  db_data:
